<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Terms and Conditions.aspx.cs" Inherits="Terms_and_Conditions" %>

<asp:Content ID="Content1" ContentPlaceHolderID="headContent" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="Server">

    <div class="applicationWindow span10 offset1">

        <div class="modal-header">George Polley Motorsports Website Terms & Conditions of Use</div>
        <div class="modal-body">
            <b>Terms and Conditions of Use</b>

            <p>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS SITE</p>

            <p>By using this site, you signify your assent to these terms of use. If you do not agree to these terms of use, please do not use this site.</p>

            <b>RESTRICTIONS ON USE OF MATERIALS</b>
            <p>This site is owned and operated by George Polley Motorsports.</p>

            <p>
                No material from this site may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, 
except that you may download one copy of the materials on any single computer for your non-commercial use only, provided that you keep intact all copyright and other proprietary notices.
            </p>

            <p>
                Modification of the materials or use of the materials for any other purpose is a violation of George Polley Motorsports copyright and other proprietary rights.
The use of any such material on any other website or networked computer environment is prohibited. Except as otherwise indicated on this site and except for the trademarks, 
service marks and trade names of other companies that are displayed on this site, all trademarks, service marks and trade names are proprietary to George Polley Motorsports
            </p>

            <p>
                In the event that you download any software from this site, the software, including any files, images incorporated in or generated by the software, and data accompanying the software (collectively the “software”) 
are non-exclusively licensed to you by George Polley Motorsports.
            </p>

            <p>
                George Polley Motorsports does not transfer title to the software to you. George Polley Motorsports retains full and complete title to the software, and all intellectual property rights therein. 
You may not redistribute, sell, decompile, reverse engineer, disassemble, or otherwise reduce the software to a human-perceivable form.
            </p>

            <b>DISCLAIMER</b>
            <p>
                The materials in this site are provided “as is” and without warranties of any kind either express or implied. To the fullest extent permissible pursuant to applicable law, 
www.polleymotorsport.co.uk disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose.
            </p>

            <p>
                George Polley Motorsports does not warrant that the functions contained in the materials will be uninterrupted or error-free, that defects will be corrected, 
or that this site or the server that makes it available are free of viruses or other harmful components.
            </p>

            <p>
                George Polley Motorsports does not warrant or make any representations regarding the use or the results of the use of the materials in this site in terms of their correctness, accuracy, reliability, or otherwise.
            </p>

            <p>
                You (and not George Polley Motorsports) assume the entire cost of all necessary servicing, repair, or correction. Applicable law may not allow the exclusion of implied warranties, 
so the above exclusion may not apply to you.
            </p>

            <b>LIMITATION OF LIABILITY</b>
            <p>
                Under no circumstances, including, but not limited to, negligence, shall George Polley Motorsports be liable for any special or consequential damages that result from the use of, or the inability to use, the materials in this site, even if George Polley Motorsports or a George Polley Motorsports authorised representative has been advised of the possibility of such damages.
            </p>

            <p>
                In no event shall George Polley Motorsports have any liability to you for damages, losses and causes of action, whether in contract, tort (including, but not limited to, negligence), or otherwise for accessing this site.
            </p>
        </div>
    </div>
</asp:Content>

